//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfEntity02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinavtablosu
    {
        public int no { get; set; }
        public string adi { get; set; }
        public Nullable<double> vize { get; set; }
        public Nullable<double> final { get; set; }
        public Nullable<double> ortalama { get; set; }
    }
}
